[package]
name = "ttml-processor"
version = "0.1.0"
authors = ["apoint123 <108002475+apoint123@users.noreply.github.com>"]
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.106"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
# console_error_panic_hook = { version = "0.1.7" }

ttml_processor = "0.1.8"
lyrics_helper_core = "0.2.0"
serde = "1.0.228"
serde-wasm-bindgen = "0.6.5"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

cast_possible_wrap = "allow"
cast_precision_loss = "allow"
